### ISSUE TITLE
功能建议--设置默认Inbox+点击插件自动添加网页，简化步骤

### ISSUE THREAD

**Issue by LeviTK** [xc2/follow-it-later#12]

**Comment by xc2** [comment]
Thank you for your suggestion.

I’m adding a few additional notes related to it.

The extension should allow users to:

1. Set a default inbox
2. Set up shortcuts for each inbox (might requesting extra permissions)

**Comment by xc2** [comment]
I'm closing this issue as completed.

Version 0.1.3 will includes this feature and the webstore version is pending approval.
