### ISSUE TITLE
Can I modify the usage policy so that it is not sent immediately when I click the icon?

### ISSUE THREAD

**Issue by anghunk** [xc2/follow-it-later#24]
The current way to use the extension is to click the small icon to immediately send the current page to the inbox, but sometimes it may be accidentally touched or for other reasons.

Can it be made into the following form: when you click on the small icon, a pop-up window will be displayed, which lists the brief information sent, such as the recipient's email address, title, content and other metadata, and can support editing of the sent content.

**Comment by xc2** [comment]
> The current way to use the extension is to click the small icon to immediately send the current page to the inbox, but sometimes it may be accidentally touched or for other reasons.

You could unset the default inbox to disable the 1-click sending feature

https://github.com/user-attachments/assets/cc59a944-6bfc-4059-a462-2a550149887a

Let me know if you have any thought about this.

> Can it be made into the following form: when you click on the small icon, a pop-up window will be displayed, which lists the brief information sent, such as the recipient's email address, title, content and other metadata, and can support editing of the sent content.

Great idea! I'm glad to include those features in the upcoming releases.
